### ISSUE TITLE
DVD-Video support

### ISSUE THREAD

**Issue by disc-kuraudo** [rickgaiser/neutrino#11]
Do you think launching DVD-Video ISOs could be possible by specifying/mounting the ISO and firing up either the stock DVD player or an absolute path to a patched DVD player ELF to get RGB output without the green tint?

Patched DVD player e.g.:
https://gbatemp.net/threads/tutorial-region-free-and-rgb-dvd-player-for-ps2.503005/

**Comment by disc-kuraudo** [comment]
Anything new on this?

**Comment by rickgaiser** [comment]
Not really. I added support for loading ELF files, and tried starting the dvd player ELF, but it does many things different from what games are allowed to do. I investigated the differences and tried many things to fix it, but making this work currently requires too much work.

**Comment by jksherk** [comment]
Anything update on this? it should be really cool to turn the tiny ps2 slim into a DVD media center

**Comment by israpps** [comment]
> Anything update on this? it should be really cool to turn the tiny ps2 slim into a DVD media center

Bind the DVD player as an update and done

**Comment by jksherk** [comment]
> > Anything update on this? it should be really cool to turn the tiny ps2 slim into a DVD media center
> 
> Bind the DVD player as an update and done

However, developers previously said that it would be difficult to implement.

**Comment by israpps** [comment]
> > > Anything update on this? it should be really cool to turn the tiny ps2 slim into a DVD media center
> > 
> > 
> > Bind the DVD player as an update and done
> 
> However, developers previously said that it would be difficult to implement.

Doing what I said doesn't require any coding. It's just binding a cracked official DVDPlayer posted on some website and binding it to the card with KELFBinder so the console menu uses it to load the movies.

Google `ps2 dvdplayer modifications`

**Comment by jksherk** [comment]
> > > > Anything update on this? it should be really cool to turn the tiny ps2 slim into a DVD media center
> > > 
> > > 
> > > Bind the DVD player as an update and done
> > 
> > 
> > However, developers previously said that it would be difficult to implement.
> 
> Doing what I said doesn't require any coding. It's just binding a cracked official DVDPlayer posted on some website and binding it to the card with KELFBinder so the console menu uses it to load the movies.
> 
> Google `ps2 dvdplayer modifications`

Thank you for your explanation; I've seen this software and it's really good. I think I might have expressed myself incorrectly, as what I meant to say is that I want to directly run DVD video ISO files. I already have a modchip that can read DVDs from all regions, but I want to read the DVD ISOs directly from SMB, so that I don't need to use the discs, just like when I play PS2 games. Both the original Xbox and PS3 can do this, but they aren't as quiet or as reliable as the PS2.
