### ISSUE TITLE
[SCES_511.76] Disney's Treasure Planet freeze on stratup (UDPBD)

### ISSUE THREAD

**Issue by AKuHAK** [rickgaiser/neutrino#14]
[SCES-51176.txt](https://github.com/rickgaiser/neutrino/files/12567711/SCES-51176.txt)
debug logs, game freeze on launch.
http://redump.org/disc/237/

There is suspicious phrase _The disk reports itself as an ISO disk._ looks like some sort of antipiracy.

**Comment by rickgaiser** [comment]
PSX2 shows the same message, and works.

I tried this game on a 70k, choose 50Hz option:
I can get into the level, only the sound hangs.

**Comment by rickgaiser** [comment]
Can you try this game again with the latest neutrino?
For me it now works using UDPBD.

**Comment by rickgaiser** [comment]
This game suffers from a buffer overrun issue, causing random (or sometimes when you're lucky no) issues on different versions of neutrino.

See also #43 

Fixed in the latest version by enabling compatibility mode '7'. `-gc=7`
