### ISSUE TITLE
[SLUS_207.01] Scooby-Doo! Mystery Mayhem (USA)

### ISSUE THREAD

**Issue by Sleepyy20** [rickgaiser/neutrino#19]
When starting a new game, the cutscene freezes in Scooby doo Mystery Mayhem in the US version, in the European version this problem does not occur. Is there a way to fix a huge fps drop in one part of the game?

**Comment by israpps** [comment]
Interesting!

The opposite of what happens with shadow of the colossus. The pal version was kinda problematic while USA version worked like a charm

I doubt it's related to this issue, but mentioning it felt worth it

**Comment by Sleepyy20** [comment]
I forgot to mention, this is also a problem in opl

**Comment by rickgaiser** [comment]
I just tested this game on the latest neutrino. Everything seems fine to me.
Can someone confirm this game works as expected?

Tested on a real ps2 with udpbd.
