### ISSUE TITLE
[SLUS-21111] Scarface - The World Is Yours (USA)

### ISSUE THREAD

**Issue by tekno9** [rickgaiser/neutrino#29]
When starting the game using Neutrino, after a few moments of black screen, I am taken to the memory card browser screen. OPL works perfectly.

SCPH-90010, Neutrino 1.3.1 and "lastest" build, USB

**Comment by rickgaiser** [comment]
This issue has been fixed here in commit https://github.com/rickgaiser/neutrino/commit/61bdb3685369b221d9111e19658fdaa753c9396c

It will be available in the next release.

Thank you for testing!
