### ISSUE TITLE
wLE > neutrino > udpbd-vexfat

### ISSUE THREAD

**Issue by 10522** [rickgaiser/neutrino#36]
Is it possible to use wLE > neutrino > udpbd-vexfat? UDPBD-Server doesn't work anymore because the latest version for Windows is still not compiled (more details [here](https://github.com/israpps/udpbd-server/issues/1)). Also it is not as user-friendly as udpbd-vexfat. By the way, is it possible to implement the following algorithm:

1. Set up config files (only required once).
2. Starting udpbd-vexfat.
3. Running neutrino via wLE.
4. Connecting neutrino to udpbd-vexfat.
5. Displaying a simple list of games (white letters on a black background as in DKWDRV).

**Comment by awaken1ng** [comment]
> By the way, is it possible to make such an algorithm (it already works for udpbd-server) for udpbd-vexfat:

If someone makes a GUI that can list games from original udpbd-server, then it should also work on udpbd-vexfat.

**Comment by rickgaiser** [comment]
> Can you do this please?

I've got too much things to do, and too little time. If I ever find the time to make a UI/GUI then I will, but don't count  on it.

> Also, is it possible to change neutrino so that it works again via OPLNEUTRINO UDPBD?

You can ask crt0 to open source OPLNEUTRINO. He should do that anyway. Then changing it to be compatible with the latest neutrino would be easy. But what's the incompatibility anyway? As I understand it OPLNEUTRINO should support neutrino 1.2.0, and the command line interface should still be compatible.

**Comment by AKuHAK** [comment]
@10522 I will answer on behalf of repo owner. No, nothing you suggest is not possible. App creator should not deal with hacks that are not related to his project, it's hack creator responsibility to make all this work on his side. Re-asm only sounds interesting, but in fact it's the most difficult programming in the world. The level of complexity is similar to, for example, if someone asks you to add usb support inside PS2 game, like "make me Ratchet and Clank to load my customs skin from usb". When you see words like re-asm, hacking without source, level of complexity is about that high.
