### ISSUE TITLE
Neutrino GSM

### ISSUE THREAD

**Issue by Andre-Cardozo-Web** [rickgaiser/neutrino#39]
When trying to use GSM - Graphics synthesizer mode selector before opening the game through the Neutrino Plugin - I get a static black screen - I do this by using a separate GSM ELF before opening +XEB - Since I can only open Neutrino at the moment through +XEB - +XEB itself does not open and crashes on the black screen - So I do not know if Neutrino is compatible with opening GSM before it - When trying to use the GSM plugin within the +XEB interface itself I also get a black screen - Will Neutrino be compatible with GSM in the future? - If so, how will I go about getting through the +XEB interface? - Thanks

**Comment by rickgaiser** [comment]
GSM is not supported here. If you have any bugs related to GSM then you'll have to ask the developers of GSM (I don't think they are still active).

GSM will be integrated into neutrino in the future, but in a stripped down form. Only to support forcing progressive modes. Not to support nearest-pixel-stretching to higher resolutions.

**Comment by Andre-Cardozo-Web** [comment]
> 10522

Thank you very much

**Comment by Andre-Cardozo-Web** [comment]
> GSM is not supported here. If you have any bugs related to GSM then you'll have to ask the developers of GSM (I don't think they are still active).
> 
> GSM will be integrated into neutrino in the future, but in a stripped down form. Only to support forcing progressive modes. Not to support nearest-pixel-stretching to higher resolutions.

Thank you very much - But I still face Problems - I will explain - The Developer said at the beginning of the psx-place Topic mentioned by User 10522 above "as a bonus exclusion, Oplneutrino is supporting GSM features and Cheats, which are not supported by Neutrino standalone as standard (without external helper tools) or any other current GUI/frontends for Neutrino*" - This was my suspicion as a regular user..

I tested OPLNEUTRINO - With 4 games here and without success - GSM cannot be implemented either before or after - If implemented before OPLNEUTRINO - Black Screen - If implemented inside the OPLNEUTRINO interface - I also encounter black screen - Definitely as the Lord said: "GSM is not supported here." - This means that I am still stuck with the same problems, But what has changed is only the Neutrino release interfaces that are now available to me which are (OPLNEUTRINO and +XEB ) ..

I also have a BLACK SCREEN even without calling GSM - I would also like to know if I should still format the HDD and put the games in the DVD folder - Because even seeing the Games List on the HDD page when I click to open the game I am directed to the console Browser - Thank you very much and I will continue following the NEUTRINO Application Updates - Thank you

**Comment by rickgaiser** [comment]
I can't help you with OPLNEUTRINO or GSM. They are other projects by other developers. I can only help you with neutrino.

> I would also like to know if I should still format the HDD and put the games in the DVD folder - Because even seeing the Games List on the HDD page when I click to open the game I am directed to the console Browser

neutrino supports both exfat and pfs formatted HDD, but I don't think OPLNEUTRINO supports this.

**Comment by Andre-Cardozo-Web** [comment]
> neutrino supports both exfat and pfs formatted HDD, but I don't think OPLNEUTRINO supports this.

Thank you very much Mr. Rickgaiser for clarifying all my doubts - Congratulations on the project - Gratitude and respect and my feelings for your work - Thank you
