### ISSUE TITLE
(discussion) mass1 support

### ISSUE THREAD

**Issue by AKuHAK** [rickgaiser/neutrino#50]
As currently ps2sdk bdm cannot handle properly multiple devices connected, neutrino will crash if there are more than one device on the bus due to broken file/directory descriptors. It will crash regardless which device trying to access.
I opened this issue as there exist some workarounds that can be applied until (if) the issue will be fixed in ps2sdk. Nhddl for example is doing dopen for all mass devices after 2 seconds for each. @KrahJohlito were implementing callback inside bdm and waits until all callbacks come to the user.
I advice to create cli option for delay during boot, like `--delay 5` (5 seconds delay).

**Comment by rickgaiser** [comment]
The root cause of this bug needs to be found and fixed. Creating workarounds in all applications is a waste of time.
It looks like a bug in the fatfs implementation in ps2sdk to me. If this bug bugs me I'll look into that first.
