### ISSUE TITLE
Running iso and elf at the same time

### ISSUE THREAD

**Issue by mtmrc** [rickgaiser/neutrino#51]
If it is even possible, could you add an option to mount iso file to DVD without booting it, so we could run elfs like Xploder HDTV that will then boot mounted iso.

**Comment by rickgaiser** [comment]
No. Neutrino does not support ELF's that try to manipulate the behaviour of neutrino.
So no GSM, no Xploder, no cheatdevice, etc...

However, a mode that forces progressive scan only is planned in the future for neutrino.
So only 480i -> 480p and 576i -> 576p.
