### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Windows10User2** [rickgaiser/neutrino#52]
I just noticed [Neutrino's GitHub repository](https://github.com/rickgaiser/neutrino) says Neutrino doesn't have an user interface and instead it's meant to be integrated as a backend to a frontend (user interface). It also refers uLE, XEB+, OPL and any new user interface as possible user interfaces and that this makes Meutrino much more easy to maintain and allows many more applications to be made using neutrino as the backend. [Neutrino's GitHub repository](https://github.com/rickgaiser/neutrino) also says that Neutrino is a command line application, to get the most out of it the user will need to run it from the command line (using [ps2link](https://github.com/ps2dev/ps2link) and [ps2client](https://github.com/ps2dev/ps2client), for instance) and alternatively a more user friendly GUI from one of the following third-party projects can be used but with a limited feature set: said [XEB+ neutrino Launcher Plugin](https://github.com/sync-on-luma/xebplus-neutrino-loader-plugin) and [OPL version](https://www.psx-place.com/threads/opl-based-gui-frontend-for-neutrino.42166/) but also [NHDDL](https://github.com/pcm720/nhddl) and [RETROLauncher](https://github.com/Spaghetticode-Boon-Tobias/RETROLauncher). Isn't this contradictory? If said third-party loaders have a limited feature set then why should they be used to run Neutrino instead of running it via command line? Also, which features are those that aren't present in a GUI?

**Comment by rickgaiser** [comment]
> It also refers uLE, XEB+, OPL and any new user interface as possible user interfaces

I'll reword the first paragraph. It was written when there where no GUI made yet, referring to possible future implementations. But the future is here already.

> Isn't this contradictory? If said third-party loaders have a limited feature set then why should they be used to run Neutrino instead of running it via command line?

It's the users choice:
- command line: full feature set, complex to use
- GUI: limited feature set, easy to use

> Also, which features are those that aren't present in a GUI?

I can't comment on all features of all loaders. I would expect a good loader to have most bsd's and usecases covered, but never all. But perhaps you can provide me 1 GUI that claims to support all feautes?

Closing as this is not an issue.

**Comment by Windows10User2** [comment]
> > It also refers uLE, XEB+, OPL and any new user interface as possible user interfaces
> 
> I'll reword the first paragraph. It was written when there where no GUI made yet, referring to possible future implementations. But the future is here already.
> 
> > Isn't this contradictory? If said third-party loaders have a limited feature set then why should they be used to run Neutrino instead of running it via command line?
> 
> It's the users choice:
> 
>     * command line: full feature set, complex to use
> 
>     * GUI: limited feature set, easy to use
> 
> 
> > Also, which features are those that aren't present in a GUI?
> 
> I can't comment on all features of all loaders. I would expect a good loader to have most bsd's and usecases covered, but never all. But perhaps you can provide me 1 GUI that claims to support all feautes?
> 
> Closing as this is not an issue.

I don't know, hence why I asked.

**Comment by israpps** [comment]
@rickgaiser hey man.

I have a question. are you against a PR to add into neutrino a "developer mode"

Where neutrino can pull parameters via EE SIO/PPC SIO instead of argv?

Just asking b4 coding it while aiming to PR it

**Comment by rickgaiser** [comment]
This sounds a lot like a tty on linux, which is a great idea. But then it should not be implemented in neutrino, but in a shell like program. This can be a simple terminal that understands a few simple commands, like `cd` and `ls`. And also be able to start an application with arguments.

In my current setup I have an MC that boots directly into ps2link (using ps2bbl). I use ps2client as the 'terminal', but it's not an optimal solution.

The same can be done with an EE SIO/PPC SIO terminal/loader, but it won't be possible to load the ELF itself over this connection I think?

**Comment by Windows10User2** [comment]
> @rickgaiser hey man.
> 
> I have a question.what do you think about a PR to add a "developer mode"?
> 
> Where neutrino can pull parameters via EE SIO/PPC SIO instead of argv?
> 
> Just asking b4 coding it while aiming to PR it



> This sounds a lot like a tty on linux, which is a great idea. But then it should not be implemented in neutrino, but in a shell like program. This can be a simple terminal that understands a few simple commands, like `cd` and `ls`. And also be able to start an application with arguments.
> 
> In my current setup I have an MC that boots directly into ps2link (using ps2bbl). I use ps2client as the 'terminal', but it's not an optimal solution.
> 
> The same can be done with an EE SIO/PPC SIO terminal/loader, but it won't be possible to load the ELF itself over this connection I think?

What is the HD Loader format? Does it have to do with the file system or partition scheme? Are the games in the UL, ISO or ZSO formats?

**Comment by Windows10User2** [comment]
> > It also refers uLE, XEB+, OPL and any new user interface as possible user interfaces
> 
> I'll reword the first paragraph. It was written when there where no GUI made yet, referring to possible future implementations. But the future is here already.
> 
> > Isn't this contradictory? If said third-party loaders have a limited feature set then why should they be used to run Neutrino instead of running it via command line?
> 
> It's the users choice:
> 
> * command line: full feature set, complex to use
> * GUI: limited feature set, easy to use
> 
> > Also, which features are those that aren't present in a GUI?
> 
> I can't comment on all features of all loaders. I would expect a good loader to have most bsd's and usecases covered, but never all. But perhaps you can provide me 1 GUI that claims to support all feautes?
> 
> Closing as this is not an issue.

It seems NHDDL supports all BSDs.

**Comment by rickgaiser** [comment]
Try launching an APA game or a real DVD. My point is valid and this is not a discussion.

**Comment by Windows10User2** [comment]
> Try launching an APA game or a real DVD. My point is valid and this is not a discussion.

I never had a PS2 HDD and NHDDL's GitHub repo says it can launch games from an HDD. APA game or ISO/ZSO? Neutrino's GitHub repo doesn't even mention APA. I didn't know Neutrino could launch games from a real DVD. OPL can't.

**Comment by Windows10User2** [comment]
> Try launching an APA game or a real DVD. My point is valid and this is not a discussion.

I never had a PS2 HDD and NHDDL's GitHub repo says it can launch games from an HDD. APA game or ISO/ZSO? Neutrino's GitHub repo doesn't even mention APA. I didn't know Neutrino could launch games from a real DVD (and I guess CD). OPL can't. Usecases? You mean, what OPL Manager downloads? Backing Store Drivers? Why not call them Block Devices, like OPL's GitHub repo and Neutrino's afterwards? If using a virtual HDD image on a PS2 Sim (or Fat), will it have the HDD compatibility?

Also, Neutrino's GitHub repo says:

"The following CD/DVD emulation drivers are supported:

No: using original CD's / DVD's in the optical drive".

"The following HDD emulation drivers are supported:

No: using ATA HDD in the PS2".

This is misleading because it makes users think Neutrino doesn't support original CDs and DVDs in the optical drive as well as a ATA HDD on the PS2. Does Neutrino support IDE/PATA HDDs, SSDs and SSHDs?

**Comment by Windows10User2** [comment]
> Try launching an APA game or a real DVD. My point is valid and this is not a discussion.

I never had a PS2 HDD and NHDDL's GitHub repo says it can launch games from an HDD. APA game or ISO/ZSO? Neutrino's GitHub repo doesn't even mention APA. I didn't know Neutrino could launch games from a real DVD (and I guess CD). OPL can't. What are usecases? Backing Store Drivers? Why not call them Block Devices, like OPL's GitHub repo and Neutrino's afterwards? If using a virtual HDD image on a PS2 Sim (or Fat), will it have the HDD compatibility?

Also, Neutrino's GitHub repo says:

"The following CD/DVD emulation drivers are supported:

No: using original CD's / DVD's in the optical drive".

"The following HDD emulation drivers are supported:

No: using ATA HDD in the PS2".

This is misleading because it makes users think Neutrino doesn't support original CDs and DVDs in the optical drive as well as a ATA HDD on the PS2. Does Neutrino support IDE/PATA HDDs, SSDs and SSHDs?

**Comment by Windows10User2** [comment]
> Try launching an APA game or a real DVD. My point is valid and this is not a discussion.

I never had a PS2 HDD and NHDDL's GitHub repo says it can launch games from an HDD.

APA game or ISO/ZSO? Neutrino's GitHub repo doesn't even mention APA.

I didn't know Neutrino could launch games from a real DVD (and I guess CD). OPL can't. Why don't you mention DVDs (and CDs, if supported) on the "Backing Store Driver" section together with USB, MX4SIO, ATA, UDPBD and iLink, then?

What are usecases?

Backing Store Drivers? Why not call them Block Devices, like OPL's GitHub repo and Neutrino's afterwards? If using a virtual HDD image on a PS2 Sim (or Fat), will it have the HDD compatibility?

Also, Neutrino's GitHub repo says:

"The following CD/DVD emulation drivers are supported:

No: using original CD's / DVD's in the optical drive".

"The following HDD emulation drivers are supported:

No: using ATA HDD in the PS2".

This is misleading because it makes users think Neutrino doesn't support original CDs and DVDs in the optical drive as well as a ATA HDD on the PS2. Does Neutrino support IDE/PATA HDDs, SSDs and SSHDs?

**Comment by Windows10User2** [comment]
> Try launching an APA game or a real DVD. My point is valid and this is not a discussion.

I never had a PS2 HDD and NHDDL's GitHub repo says it can launch games from an HDD.

APA game or ISO/ZSO? Neutrino's GitHub repo doesn't even mention APA.

I didn't know Neutrino could launch games from a real DVD (and I guess CD). OPL can't. Why don't you mention DVDs (and CDs, if supported) on the "Backing Store Driver" section together with USB, MX4SIO, ATA, UDPBD and iLink, then?

What are usecases?

Backing Store Drivers? Why not call them Block Devices, like OPL's GitHub repo and Neutrino's afterwards?

Neutrino's GitHub repo says "iLink / IEEE1394 (sd)". Since when i.LINK uses SD? Doesn't it use its own devices?

Also, Neutrino's GitHub repo says:

"The following CD/DVD emulation drivers are supported:

No: using original CD's / DVD's in the optical drive".

"The following HDD emulation drivers are supported:

No: using ATA HDD in the PS2".

This is misleading because it makes users think Neutrino doesn't support original CDs and DVDs in the optical drive as well as a ATA HDD on the PS2. Does Neutrino support IDE/PATA HDDs, SSDs and SSHDs?

**Comment by rickgaiser** [comment]
Bug reports are welcome, but please don't bother me again with user questions or nitpicking on github.
You can use https://discord.gg/uYhkSdve for user questions

**Comment by Windows10User2** [comment]
> Bug reports are welcome, but please don't bother me again with user questions or nitpicking on github. You can use https://discord.gg/uYhkSdve for user questions

You're not forced to answer, it's not my fault for not being clear. I already went there, my questions weren't answered and I was told to go here.

**Comment by Windows10User2** [comment]
> Try launching an APA game or a real DVD. My point is valid and this is not a discussion.

But Neutrino itself doesn't support SMB and MMCE.
