### ISSUE TITLE
Black & White ("Greyscale") NTSC games on a PAL console

### ISSUE THREAD

**Issue by jonasrk** [rickgaiser/neutrino#54]
Hi friends, thanks all for your great work!

I'm using neutrino via [xebplus-neutrino-loader-plugin](https://github.com/sync-on-luma/xebplus-neutrino-loader-plugin) and stream games from my windows PC.

This all works great (and very fast), but when I launch NTSC games on my PAL console, they are black and white only. When I launch the same games via OPL / smb, I can see colors normally.

Difficult to judge for me of this is a neutrino issue or not.

Do you happen to have any guidance on how I might be able to resolve this? :)

**Comment by jonasrk** [comment]
So for those who are coming after me, my fix was super easy: "YFix NTSC to PAL patcher" for my NTSC iso. No I can play happily on my PAL PS2 via XEB / Neutrino / UDPBD. 🙂

**Comment by rickgaiser** [comment]
I need a little more clarification. My current assumptions:
- You are using a PAL ps2, with PAL TV
- You used a composite cable (not RGB or component)
- On OPL you enabled GSM and changed the CRTC output from NTSC to PAL

Are these correct?

**Comment by jonasrk** [comment]
Hi @rickgaiser and thanks. Yes, all three are correct! :) I'm picking up an RGB cable today, so hopefully that will be an even better solution then patching the iso. Either way, thanks a lot for your hard work on these awesome tools! :)

**Comment by jonasrk** [comment]
Just wanted to report back here again that switching to an RGB cable did indeed also fix my issue with (non-patched) NTSC games. :)
