### ISSUE TITLE
Issue with UDPBD Server

### ISSUE THREAD

**Issue by 10522** [rickgaiser/neutrino#9]
UDPBD Server gives an error "Invalid cmd: 0x1". Same with OPL Beta 1.2.0 1973 UDPBD, although Neutrino via USB works well.

**Comment by rickgaiser** [comment]
I use UDPBD server daily on linux, and I never have issues. I use this one:
https://gitlab.com/ps2max/udpbd-server

Are you using this server, or another one?

**Comment by rickgaiser** [comment]
Closing this issue becouse UDPBD on neutrino works perfectly.

Perhaps you can open an issue on the udpbd-server you are using.
